name 'designate'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cookbook-openstack-dnsaas'
long_description 'Installs/Configures cookbook-openstack-dnsaas'
version '0.1.0'

depends 'apt'
depends 'database'
depends 'python'
depends 'sysctl'
depends 'rabbitmq'
